name: 'Claude Self-Learning Review'
description: 'Analyzes recent commits to identify patterns and improve project rules automatically'
author: 'Valmarelox'

branding:
  icon: 'book-open'
  color: 'orange'

inputs:
  claude_code_oauth_token:
    description: 'Claude Code OAuth token for authentication'
    required: false

  anthropic_api_key:
    description: 'Anthropic API key (alternative to OAuth token)'
    required: false

  days_to_analyze:
    description: 'Number of days of git history to analyze'
    required: false
    default: '7'

  prompt:
    description: 'Custom prompt for Claude (completely overrides default analysis)'
    required: false

  additional_prompt:
    description: 'Extra context appended to the default prompt (ignored if prompt is set)'
    required: false

  rules_path:
    description: 'Path to rules directory'
    required: false
    default: '.claude/rules'

  rules_file:
    description: 'Path to main rules file'
    required: false
    default: 'CLAUDE.md'

  max_rule_lines:
    description: 'Maximum lines per rule file'
    required: false
    default: '200'

  allowed_tools:
    description: 'Tools Claude is allowed to use'
    required: false
    default: 'Bash(git *),Edit,Write,Read,Glob,Grep'

  model:
    description: 'Claude model to use'
    required: false
    default: ''

  analyze_prs:
    description: 'Analyze merged PR review comments for feedback patterns (requires GITHUB_TOKEN)'
    required: false
    default: 'true'

outputs:
  pr_number:
    description: 'PR number if one was created'
    value: ${{ steps.claude-review.outputs.pr_number }}

  pr_url:
    description: 'PR URL if one was created'
    value: ${{ steps.claude-review.outputs.pr_url }}

runs:
  using: 'composite'
  steps:
    - name: Build prompt from template
      id: build-prompt
      shell: bash
      env:
        DAYS_TO_ANALYZE: ${{ inputs.days_to_analyze }}
        RULES_FILE: ${{ inputs.rules_file }}
        RULES_PATH: ${{ inputs.rules_path }}
        MAX_RULE_LINES: ${{ inputs.max_rule_lines }}
        ANALYZE_PRS: ${{ inputs.analyze_prs }}
        ADDITIONAL_PROMPT: ${{ inputs.additional_prompt }}
      run: |
        PROMPT=$(sed \
          -e "s|__DAYS_TO_ANALYZE__|${DAYS_TO_ANALYZE}|g" \
          -e "s|__RULES_FILE__|${RULES_FILE}|g" \
          -e "s|__RULES_PATH__|${RULES_PATH}|g" \
          -e "s|__MAX_RULE_LINES__|${MAX_RULE_LINES}|g" \
          "${GITHUB_ACTION_PATH}/prompt.md")

        # Remove PR analysis section if disabled
        if [ "${ANALYZE_PRS}" = "false" ]; then
          PROMPT=$(echo "$PROMPT" | awk '/<!-- BEGIN:PR_ANALYSIS -->/{skip=1;next}/<!-- END:PR_ANALYSIS -->/{skip=0;next}!skip')
        fi

        # Append additional context if provided
        if [ -n "${ADDITIONAL_PROMPT}" ]; then
          PROMPT="${PROMPT}

        ## Additional Context
        ${ADDITIONAL_PROMPT}"
        fi

        {
          echo "prompt<<PROMPT_DELIMITER_EOF"
          echo "$PROMPT"
          echo "PROMPT_DELIMITER_EOF"
        } >> "$GITHUB_OUTPUT"

    - name: Build claude args
      id: build-args
      shell: bash
      env:
        ALLOWED_TOOLS: ${{ inputs.allowed_tools }}
        MODEL: ${{ inputs.model }}
      run: |
        ARGS="--allowed-tools ${ALLOWED_TOOLS}"
        if [ -n "${MODEL}" ]; then
          ARGS="${ARGS} --model ${MODEL}"
        fi
        echo "claude_args=${ARGS}" >> "$GITHUB_OUTPUT"

    - name: Run Claude Self-Learning Review
      id: claude-review
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        claude_args: ${{ steps.build-args.outputs.claude_args }}
        prompt: ${{ inputs.prompt || steps.build-prompt.outputs.prompt }}
