name: 'Claude Self-Learning Review'
description: 'Analyzes recent commits to identify patterns and improve project rules automatically'
author: 'Your Name'

branding:
  icon: 'book-open'
  color: 'orange'

inputs:
  claude_code_oauth_token:
    description: 'Claude Code OAuth token for authentication'
    required: true

  anthropic_api_key:
    description: 'Anthropic API key (alternative to OAuth token)'
    required: false

  days_to_analyze:
    description: 'Number of days of git history to analyze'
    required: false
    default: '7'

  prompt:
    description: 'Custom prompt for Claude (overrides default analysis)'
    required: false

  rules_path:
    description: 'Path to rules directory'
    required: false
    default: '.claude/rules'

  rules_file:
    description: 'Path to main rules file'
    required: false
    default: 'CLAUDE.md'

  max_rule_lines:
    description: 'Maximum lines per rule file'
    required: false
    default: '200'

  allowed_tools:
    description: 'Tools Claude is allowed to use'
    required: false
    default: 'Bash(git *),Edit,Write,Read,Glob,Grep'

  model:
    description: 'Claude model to use'
    required: false
    default: ''

  analyze_prs:
    description: 'Analyze merged PR comments for feedback patterns'
    required: false
    default: 'true'

outputs:
  pr_number:
    description: 'PR number if one was created'
    value: ${{ steps.claude-review.outputs.pr_number }}

  pr_url:
    description: 'PR URL if one was created'
    value: ${{ steps.claude-review.outputs.pr_url }}

runs:
  using: 'composite'
  steps:
    - name: Run Claude Self-Learning Review
      id: claude-review
      uses: anthropics/claude-code-action@v1
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        anthropic_api_key: ${{ inputs.anthropic_api_key }}
        allowed_tools: ${{ inputs.allowed_tools }}
        model: ${{ inputs.model }}

        prompt: |
          ${{ inputs.prompt || format('You are analyzing this repository to identify patterns where Claude made mistakes,
          so you can propose rule improvements to prevent future issues.

          ## PHASE 1: Data Gathering

          ### Git History Analysis
          Run: `git log --oneline --stat --since="{0} days ago"`

          Look for commits that suggest corrections:
          - Message patterns: "fix", "revert", "correct", "cleanup", "remove unnecessary", "actually", "oops", "typo"
          - Files modified multiple times in short succession
          - Small commits following large Claude-generated commits

          For each suspicious commit, run `git show <hash>` to see the actual diff.
          Focus on WHAT was wrong in the code, not just the commit message.

          ### PR Review Comments (if available)
          Run: `gh pr list --state merged --limit 20 --json number,title,mergedAt`

          For recent merged PRs, fetch review comments:
          `gh pr view <number> --comments --json comments,reviews`

          Look for:
          - Review feedback explaining why code was wrong
          - Requested changes patterns
          - Common reviewer complaints

          If `gh` fails or no PRs exist, continue with git-only analysis.

          ## PHASE 2: Pattern Recognition

          Categorize issues found. Start with these categories, but add new ones if you discover patterns that do not fit:

          - **style**: Code formatting, naming conventions, idioms
          - **architecture**: Wrong patterns, poor structure, coupling issues
          - **overengineering**: Unnecessary abstractions, premature optimization
          - **underengineering**: Missing error handling, edge cases, validation
          - **security**: Vulnerabilities, unsafe practices
          - **testing**: Missing tests, poor test quality
          - **dependencies**: Wrong imports, version issues

          For each pattern, note:
          - Frequency (how many times it occurred)
          - Severity (how much effort to fix)
          - Concrete example from the diffs

          ## PHASE 3: Rule Proposal

          Read existing rules in {1} and {2}/.

          For each significant pattern (occurred 2+ times OR high severity):
          1. Check if an existing rule already covers it
          2. If not, draft a new rule with:
             - Clear, actionable directive
             - Brief code example (3-5 lines max showing wrong vs right)
             - Category tag

          ## PHASE 4: Output

          If patterns found worth documenting:
          - Create/update rule files
          - Create a PR with:
            - Title: "chore: update Claude rules based on recent patterns"
            - Body listing patterns found and rules added

          If no significant patterns (all one-offs or already covered):
          - Exit cleanly without creating anything
          - Optionally log what was analyzed

          ## CONSTRAINTS
          - Rule files must stay under {3} lines
          - Prioritize recurring patterns over one-offs
          - Be specific - vague rules do not help
          - Do not duplicate existing rules', inputs.days_to_analyze, inputs.rules_file, inputs.rules_path, inputs.max_rule_lines) }}
