# Example: Weekly self-learning review
# Copy this to .github/workflows/ in your repository

name: Claude Self-Learning Review

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9:00 AM UTC

  workflow_dispatch:
    inputs:
      prompt:
        description: 'Custom prompt for Claude (optional)'
        required: false
        type: string

jobs:
  self-learning-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for pattern analysis

      - name: Run Claude Self-Learning Review
        id: claude-review
        uses: your-username/claude-learn-action@v1
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          prompt: ${{ github.event.inputs.prompt }}

      - name: Upload analysis results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: claude-analysis-${{ github.run_number }}
          path: |
            .claude/
            *.log
          retention-days: 30
